workerd:
  # Configuration for the workerd container image
  image:
    repository: "ghcr.io/willswire/union/workerd"
    pullPolicy: "Always"
    tag: "1.20250204.0"
  # Service configuration for workerd
  service:
    type: "ClusterIP"
    port: 8080
  # Date used for compatibility checking
  compatibilityDate: "2023-02-28"
  # List of workers to deploy
  workers:
    - name: hello-world
      image: ghcr.io/willswire/union/hello-world:2.0.0

cloudflared:
  # Whether to enable cloudflared
  enabled: true
  # Cloudflared container image configuration
  image:
    repository: "cloudflare/cloudflared"
    tag: "2024.12.2"
  # List of tunnels to create
  tunnels:
    - workerName: "hello-world"
  userTunnel:
    # Default to quick tunnel, which only works for one worker
    enabled: false
    # Your Cloudflare account number.
    account: ""
    # The name of the tunnel this instance will serve
    tunnelName: ""
    # The ID of the above tunnel.
    tunnelId: ""
    # The secret for the tunnel.
    secret: ""
    # If true, turn on WARP routing for TCP
    enableWarp: false
    # Ingress rule hostname for workerd service
    # See https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/configure-tunnels/local-management/configuration-file/
    hostname: ""
