workerd:
  image:
    repository: "ghcr.io/willswire/union/workerd"
    pullPolicy: "Always"
    tag: "1.20250204.0"
  service:
    type: "ClusterIP"
    port: 8080
  compatibilityDate: "2023-02-28"
  workers:
    - name: hello-world
      image: ghcr.io/willswire/union/hello-world:1.0.0-arm64

cloudflared:
  enabled: true
  image:
    repository: "cloudflare/cloudflared"
    tag: "2024.12.2"
  userTunnel:
    # Default to quick tunnel
    enabled: false
    # Your Cloudflare account number.
    account: ""
    # The name of the tunnel this instance will serve
    tunnelName: ""
    # The ID of the above tunnel.
    tunnelId: ""
    # The secret for the tunnel.
    secret: ""
    # If true, turn on WARP routing for TCP
    enableWarp: false
    # Ingress rule hostname for workerd service
    # See https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/configure-tunnels/local-management/configuration-file/
    hostname: ""
