workerd:
  replicaCount: 1
  image:
    repository: ghcr.io/willswire/workforce/workerd
    pullPolicy: IfNotPresent
    tag: "1.20241214.0"
  service:
    type: ClusterIP
    port: 8080
  script: null

cloudflared:
  hostname: example.com
