workerd:
  replicaCount: 1
  image:
    repository: "ghcr.io/willswire/union/workerd"
    pullPolicy: "Always"
    tag: "1.20241214.0"
  service:
    type: "ClusterIP"
    port: 8080
  script: |
    addEventListener('fetch', event => {
      event.respondWith(handle(event.request));
    });

    async function handle(request) {
      return new Response("Hello World!");
    }

cloudflared:
  enabled: true
  image:
    repository: "cloudflare/cloudflared"
    tag: "2024.12.2"
