{{- if .Values.cloudflared.userTunnel.enabled }}
# This configmap stores the configuration used by cloudflared.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudflare-tunnel.fullname" . }}
data:
  config.yaml: |
    # Name of the tunnel you want to run
    tunnel: {{ .Values.cloudflared.userTunnel.tunnelName }}
    # The location of the secret containing the tunnel credentials
    credentials-file: /etc/cloudflared/creds/credentials.json
    # General purpose TCP routing for the network
    warp-routing:
      enabled: {{ .Values.cloudflared.userTunnel.enableWarp }}
    # Serves the metrics server under /metrics and the readiness server under /ready
    metrics: 0.0.0.0:2000
    # Autoupdates applied in a k8s pod will be lost when the pod is removed or restarted, so
    # autoupdate doesn't make sense in Kubernetes. However, outside of Kubernetes, we strongly
    # recommend using autoupdate.
    no-autoupdate: true
    # Serve the workerd service
    ingress:
      {{- range .Values.cloudflared.tunnels }}
      - hostname: {{ $.Values.cloudflared.userTunnel.hostname }}
        path: {{ .path | default "/*" }}
        service: http://workerd-{{ .workerName }}:{{ $.Values.workerd.service.port }}
      {{- end }}
      - service: http_status:404
{{- end }}
