---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
data:
  config.yaml: |
    tunnel: {{ .Release.Name }}-tunnel
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: {{ .Release.Name }}.{{ .Values.cloudflared.hostname }}
      service: http://{{ .Release.Name }}-workerd:{{ .Values.service.port }}
    - service: http_status:404
