{{- if .Values.cloudflared.userTunnel.enabled }}
# This credentials secret allows cloudflared to authenticate itself
# to the Cloudflare infrastructure.
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflare-tunnel.fullname" . }}
stringData:
  credentials.json: |-
    {
      "AccountTag": {{ .Values.cloudflared.userTunnel.account | quote }},
      "TunnelID": {{ .Values.cloudflared.userTunnel.tunnelId | quote }},
      "TunnelSecret": {{ .Values.cloudflared.userTunnel.secret | quote }}
    }
{{- end }}