{{- /* templates/configmap.yaml */ -}}
{{- range .Values.workerd.workers }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: workerd-config-{{ .name }}
data:
  config.capnp: |
    using Workerd = import "/workerd/workerd.capnp";

    const default :Workerd.Worker = (
      serviceWorkerScript = embed "worker/index.js",
      compatibilityDate = "{{ $.Values.workerd.compatibilityDate }}",
    );

    const config :Workerd.Config = (
      services = [ (name = "{{ .name }}", worker = .default) ],
      sockets = [
        ( name = "http",
          address = "*:{{ $.Values.workerd.service.port }}",
          http = (),
          service = "{{ .name }}" )
      ]
    );
---
{{- end }}
