apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-workerd
  labels:
    app: {{ .Release.Name }}-workerd
spec:
  type: {{ .Values.workerd.service.type }}
  ports:
    - port: {{ .Values.workerd.service.port }}
      targetPort: {{ .Values.workerd.service.port }}
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-workerd
