{{- /* For each worker, create a service that selects pods labeled with app: workerd and worker: <worker name> */ -}}
{{- range .Values.workerd.workers }}
apiVersion: v1
kind: Service
metadata:
  name: workerd-{{ .name }}
  labels:
    app: workerd
    worker: {{ .name }}
spec:
  type: {{ $.Values.workerd.service.type }}
  ports:
    - port: {{ $.Values.workerd.service.port }}
      targetPort: {{ $.Values.workerd.service.port }}
      protocol: TCP
  selector:
    app: workerd
    worker: {{ .name }}
---
{{- end }}
